const videoData = [
    {
        avata: require('~/assets/images/avata/avt1.jpeg'),
        name: 'jungkook',
        username: 'AbjkMRstY',
        title: 'dc:@Jean-Victor #fyp #dance #gcf',
        song: 'WDYS (Sped Up Version) - yedira & asheu',
        videoUrl: require('~/assets/videos/vd1.jpg'),
        likes: '3.24M',
        comments: '8.7K',
        saves: '131',
        shares: '29',
    },
    {
        avata: require('~/assets/images/avata/avt2.jpeg'),
        name: 'itsmewinterkyle',
        username: 'winterkyle',
        title: 'trying the trend #CapCut',
        song: '오리지널 사운드  - Wang Saoli',
        videoUrl: require('~/assets/videos/vd2.jpg'),
        likes: '1.47M',
        comments: '218',
        saves: '180.3K',
        shares: '2169',
    },
    {
        avata: require('~/assets/images/avata/avt3.jpeg'),
        name: 'r.reyesssss',
        username: 'Renata Reyes',
        title: 'Brasiuuu',
        song: 'original sound - Visit_rio_brazil',
        videoUrl: require('~/assets/videos/vd3.jpg'),
        likes: '4.55M',
        comments: '17.9K',
        saves: '438.3K',
        shares: '36K',
    },
    {
        avata: require('~/assets/images/avata/avt1.jpeg'),
        name: 'jungkook',
        username: 'AbjkMRstY',
        title: 'dc:@Jean-Victor #fyp #dance #gcf',
        song: 'WDYS (Sped Up Version) - yedira & asheu',
        videoUrl: require('~/assets/videos/vd1.jpg'),
        likes: '3.24M',
        comments: '8.7K',
        saves: '131',
        shares: '29',
    },
    {
        avata: require('~/assets/images/avata/avt2.jpeg'),
        name: 'itsmewinterkyle',
        username: 'winterkyle',
        title: 'trying the trend #CapCut',
        song: '오리지널 사운드  - Wang Saoli',
        videoUrl: require('~/assets/videos/vd2.jpg'),
        likes: '1.47M',
        comments: '218',
        saves: '180.3K',
        shares: '2169',
    },
    {
        avata: require('~/assets/images/avata/avt3.jpeg'),
        name: 'r.reyesssss',
        username: 'Renata Reyes',
        title: 'Brasiuuu',
        song: 'original sound - Visit_rio_brazil',
        videoUrl: require('~/assets/videos/vd3.jpg'),
        likes: '4.55M',
        comments: '17.9K',
        saves: '438.3K',
        shares: '36K',
    },
    {
        avata: require('~/assets/images/avata/avt1.jpeg'),
        name: 'jungkook',
        username: 'AbjkMRstY',
        title: 'dc:@Jean-Victor #fyp #dance #gcf',
        song: 'WDYS (Sped Up Version) - yedira & asheu',
        videoUrl: require('~/assets/videos/vd1.jpg'),
        likes: '3.24M',
        comments: '8.7K',
        saves: '131',
        shares: '29',
    },
    {
        avata: require('~/assets/images/avata/avt2.jpeg'),
        name: 'itsmewinterkyle',
        username: 'winterkyle',
        title: 'trying the trend #CapCut',
        song: '오리지널 사운드  - Wang Saoli',
        videoUrl: require('~/assets/videos/vd2.jpg'),
        likes: '1.47M',
        comments: '218',
        saves: '180.3K',
        shares: '2169',
    },
    {
        avata: require('~/assets/images/avata/avt3.jpeg'),
        name: 'r.reyesssss',
        username: 'Renata Reyes',
        title: 'Brasiuuu',
        song: 'original sound - Visit_rio_brazil',
        videoUrl: require('~/assets/videos/vd3.jpg'),
        likes: '4.55M',
        comments: '17.9K',
        saves: '438.3K',
        shares: '36K',
    },
    {
        avata: require('~/assets/images/avata/avt1.jpeg'),
        name: 'jungkook',
        username: 'AbjkMRstY',
        title: 'dc:@Jean-Victor #fyp #dance #gcf',
        song: 'WDYS (Sped Up Version) - yedira & asheu',
        videoUrl: require('~/assets/videos/vd1.jpg'),
        likes: '3.24M',
        comments: '8.7K',
        saves: '131',
        shares: '29',
    },
    {
        avata: require('~/assets/images/avata/avt2.jpeg'),
        name: 'itsmewinterkyle',
        username: 'winterkyle',
        title: 'trying the trend #CapCut',
        song: '오리지널 사운드  - Wang Saoli',
        videoUrl: require('~/assets/videos/vd2.jpg'),
        likes: '1.47M',
        comments: '218',
        saves: '180.3K',
        shares: '2169',
    },
    {
        avata: require('~/assets/images/avata/avt3.jpeg'),
        name: 'r.reyesssss',
        username: 'Renata Reyes',
        title: 'Brasiuuu',
        song: 'original sound - Visit_rio_brazil',
        videoUrl: require('~/assets/videos/vd3.jpg'),
        likes: '4.55M',
        comments: '17.9K',
        saves: '438.3K',
        shares: '36K',
    },
];

export default videoData;
